language: python
sudo: required
python:
  - "3.7.3"
install:
  - pip install -r requirements.txt
script:
  - mkdir .aws/
  - cd .aws && touch credentials config
  - echo "[default]\nregion=us-east-1" >> config
  - chmod 777 hackslabs.py
  - python3 hackslabs.py -h
  - python3 hackslabs.py --help
  - python3 hackslabs.py --version
  - python3 hackslabs.py -version
